const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const root=path.resolve(__dirname,'../..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
function link(url){const nodes={'consultation-link':{hidden:true},'consultation-setup':{textContent:'準備中'}};vm.runInNewContext(read('booking-link.js'),{window:{FREE_CONSULTATION_CONFIG:{webAppUrl:url}},document:{getElementById:id=>nodes[id]}});return nodes;}
test('LP link remains unavailable for missing / unsafe / dev URLs',()=>{for(const url of ['',undefined,'javascript:alert(1)','https://example.test/exec','https://script.google.com/macros/s/test/dev'])assert.equal(link(url)['consultation-link'].hidden,true);});
test('valid production URL produces secondary normal link',()=>{const url='https://script.google.com/macros/s/test-deployment/exec';assert.equal(link(url)['consultation-link'].href,url);assert.equal(link(url)['consultation-link'].hidden,false);});
test('original LP content is preserved byte-for-byte outside booking additions and the supplied trial video',()=>{const original=cp.execFileSync('git',['show','82dd038e9b3f1a99544cefb4e6c209f5626d3763:index.html'],{cwd:root,encoding:'utf8'});const restored=read('index.html').replace('\n<script src="booking-config.js" defer></script>\n<script src="booking-link.js" defer></script>','').replace(/<section id="free-consultation"[\s\S]*?<\/section>\n\n/,'');const withoutTrial=s=>s.replace(/<section id="trial"[\s\S]*?<\/section>/,"");assert.equal(withoutTrial(restored),withoutTrial(original));});
test('consultation follows price and precedes FAQ without moving fit',()=>{const s=read('index.html');assert(s.indexOf('id="price"')<s.indexOf('id="free-consultation"'));assert(s.indexOf('id="free-consultation"')<s.indexOf('<section class="fit'));assert(s.indexOf('<section class="fit')<s.indexOf('<section class="faq'));});
test('no Calendar configuration or credentials in static booking files',()=>{for(const f of ['booking-config.js','booking-link.js'])assert(!/calendarId|ownerNotificationEmail|spreadsheetId|meetingUrl|OAuth|token/.test(read(f)));});
test('form consent unchecked, required and named; default frame protection',()=>{const s=read('booking-app/index.html');assert.match(s,/<input id="consent" type="checkbox" required>/);assert.match(s,/role="alert"/);assert.match(s,/aria-describedby="error"/);assert(!/\.setXFrameOptionsMode\(/.test(read('booking-app/Code.gs')));});
test('all JavaScript files parse',()=>{for(const f of ['booking-config.js','booking-link.js','script.js'])new vm.Script(read(f));new vm.Script(read('booking-app/client-js.html').replace(/^<script>\s*/,'').replace(/<\/script>\s*$/,''));});
